spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=master;encrypt=false
    username: sa
    password: Password23
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:

  data:
    redis:
      host: localhost
      port: 6379

resilience4j:
  ratelimiter:
    instances:
      simulacaoRateLimiter:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 500ms

  circuitbreaker:
    instances:
      sqlServerCircuitBreaker:
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
